# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run all tests

on:
  push:
    branches: ["master"]
    paths:
      - src/mode/
      - tests/
      - requirements/
  pull_request:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "Run tests with Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false # Complete all jobs even if one fails
      matrix:
        python-version: ["3.10", "3.11", "3.12-dev"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install .
          make deps-test
      - name: Run tests
        run: make test
